name: facet_ml_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - ansi2html=1.9.1
  - asttokens=2.4.1
  - blas=1.0
  - blinker=1.6.2
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - ca-certificates=2024.7.2
  - certifi=2024.7.4
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cuda-cccl=12.3.101
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.99
  - cuda-opencl-dev=12.4.99
  - cuda-profiler-api=12.3.101
  - cuda-runtime=12.1.0
  - daal4py=2023.1.1
  - dal=2023.1.1
  - dash=2.14.2
  - dash-bootstrap-components=1.6.0
  - debugpy=1.8.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - filelock=3.13.1
  - flask=3.0.3
  - flask-compress=1.13
  - freetype=2.12.1
  - gmpy2=2.1.2
  - idna=3.4
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.3
  - itsdangerous=2.2.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.4.107
  - libcurand-dev=10.3.4.107
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.17
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp-base=1.3.2
  - llvmlite=0.42.0
  - lz4-c=1.9.4
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - numba=0.59.0
  - numexpr=2.8.7
  - numpy=1.25.2
  - numpy-base=1.25.2
  - openjpeg=2.4.0
  - openssl=3.2.1
  - packaging=23.2
  - pandas=2.1.4
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=10.2.0
  - platformdirs=4.2.0
  - plotly=5.22.0
  - psutil=5.9.8
  - pure_eval=0.2.2
  - pygments=2.17.2
  - pysocks=1.7.1
  - python=3.9.18
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pywin32=306
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - requests=2.31.0
  - retrying=1.3.3
  - scikit-learn=1.2.1
  - scikit-learn-intelex=2023.1.1
  - seaborn=0.12.2
  - setuptools=68.2.2
  - six=1.16.0
  - slicer=0.0.7
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.8.0
  - tenacity=8.2.3
  - tornado=6.4
  - tqdm=4.65.0
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - urllib3=2.1.0
  - wcwidth=0.2.13
  - wheel=0.41.2
  - pip:
      - absl-py==2.1.0
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - attrs==24.2.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - black==24.3.0
      - bleach==6.1.0
      - build==1.1.1
      - cloudpickle==3.0.0
      - cycler==0.12.1
      - defusedxml==0.7.1
      - docopt==0.6.2
      - fastjsonschema==2.20.0
      - fonttools==4.49.0
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - fvcore==0.1.5.post20221221
      - git-filter-repo==2.45.0
      - grpcio==1.62.1
      - h5py==3.10.0
      - hydra-core==1.3.2
      - imageio==2.34.0
      - importlib-resources==6.1.2
      - iopath==0.1.9
      - ipython==8.12.3
      - joblib==1.3.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - mistune==3.0.2
      - msgpack==1.1.0
      - mypy-extensions==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - networkx==3.2.1
      - omegaconf==2.3.0
      - opencv-python==4.9.0.80
      - pandocfilters==1.5.1
      - pathspec==0.12.1
      - pip==24.2
      - pipreqs==0.5.0
      - portalocker==2.8.2
      - prompt-toolkit==3.0.43
      - protobuf==5.26.0
      - pyarrow==17.0.0
      - pycocotools==2.0.7
      - pyparsing==3.1.1
      - pyproject-hooks==1.0.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - ray==2.35.0
      - referencing==0.35.1
      - rpds-py==0.20.0
      - scikit-image==0.22.0
      - scipy==1.12.0
      - segment-anything==1.0
      - shap==0.40.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - threadpoolctl==3.3.0
      - tifffile==2024.2.12
      - tinycss2==1.3.0
      - tomli==2.0.1
      - torchaudio==2.2.1
      - torchvision==0.17.1
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - webencodings==0.5.1
      - werkzeug==3.0.1
      - yacs==0.1.8
      - yarg==0.1.9